# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_fqtkWrapper_wrappers", use_symbols = TRUE, package_name = "fqtkWrapper")

#' @usage NULL
#' @useDynLib fqtkWrapper, .registration = TRUE
NULL

#' Exposes the `fqtk demux` functionality as a Rust function that can be called from R.
#' 
#' @param inputs A character vector of input FASTQ file paths.
#' @param max_mismatches An integer specifying the maximum number of mismatches allowed during demultiplexing.
#' @param read_structures A character vector specifying the read structures for parsing barcodes and sequences.
#' @param sample_metadata A string specifying the path to the CSV or TSV file containing sample metadata.
#' @param output A string specifying the output directory or file path for demultiplexed results.
#' 
#' @return A character string indicating success.
#' @export
fqtk_demux <- function(inputs, max_mismatches, read_structures, sample_metadata, output) .Call(wrap__fqtk_demux, inputs, max_mismatches, read_structures, sample_metadata, output)


# nolint end
